### ISSUE TITLE
大神，请问updatenet 我们用官方给的那个模型测试为什么达不到论文中的效果呢

### ISSUE THREAD

**Issue by lkw666** [HonglinChu/UpdateNet#2]
大神，请问updatenet 我们用官方给的那个模型在VOT2018中测试为什么达不到论文中的效果呢，EAO结果只有0.353,是我的那个地方的设置有问题吗，我用的win10系统

**Comment by lkw666** [comment]
已经解决，我数据集的问题，非常感谢

**Comment by HonglinChu** [comment]
UpdateNet需要多阶段训练，同时每个阶段对学习率比较敏感，有条件的同学尽量把学习步长设置的小一些，代价就是训练评估的次数增多；如果学习率选择的不好，结果只有0.353是很正常的，第一阶段学习率如果选择的合适，需要达到0.365~0.375，这个时候可以进行第二阶段的训练；第二阶段的结果依然需要达到0.375以上，（根据我们之前训练总结的经验），这个时候才可以进行第三阶段的训练；第三阶段的训练虽然有可能超过0.383（DaSiamRPN原文结果），但是超过0.393(UpdateNet原文结果)还是有很大困难。可以达到0.38x~0.39x，而我自己在第三阶段的最好的训练结果是0.403，也是出乎我的意料，这个学习率的确太难找了，而且这样的模型训练精度我认为是不可复现的。关于多阶段的训练方法可以参考UpdateNet文件夹的readme

**Comment by HonglinChu** [comment]
UpdateNet需要多阶段训练，同时每个阶段对学习率比较敏感，有条件的同学尽量把学习步长设置的小一些，代价就是训练评估的次数增多；如果学习率选择的不好，结果只有0.353是很正常的，第一阶段学习率如果选择的合适，需要达到0.3650.375，这个时候可以进行第二阶段的训练；第二阶段的结果依然需要达到0.375以上，（根据我们之前训练总结的经验），这个时候才可以进行第三阶段的训练；第三阶段的训练虽然有可能超过0.383（DaSiamRPN原文结果），但是超过0.393(UpdateNet原文结果)还是有很大困难。可以达到0.38x0.39x，而我自己在第三阶段的最好的训练结果是0.403，也是出乎我的意料，这个学习率的确太难找了，而且这样的模型训练精度我认为是不可复现的。关于多阶段的训练方法可以参考UpdateNet文件夹的readme
